# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZP7aauv0Hrw0Xhbu_EgHg6S1FFM4TMIZ
"""


```python
from rdkit import Chem
from rdkit.Chem import Draw
import streamlit as st
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv, global_mean_pool

st.set_page_config(
    page_title="AI Drug Binding Predictor", page_icon="💊", layout="centered"
)

# Model Definition
class EnhancedGCN(nn.Module):
    def __init__(self, in_channels=4, hidden_channels=128):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.bn1 = nn.BatchNorm1d(hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.bn2 = nn.BatchNorm1d(hidden_channels)
        self.conv3 = GCNConv(hidden_channels, 64)
        self.fc1 = nn.Linear(64, 32)
        self.fc2 = nn.Linear(32, 1)

    def forward(self, x, edge_index, batch):
        x = F.relu(self.bn1(self.conv1(x, edge_index)))
        x = F.relu(self.bn2(self.conv2(x, edge_index)))
        x = F.relu(self.conv3(x, edge_index))
        x = global_mean_pool(x, batch)
        x = F.relu(self.fc1(x))
        return self.fc2(x)

@st.cache_resource
def load_model():
    model = EnhancedGCN(in_channels=4, hidden_channels=128)
    model.load_state_dict(
        torch.load("gcn_binding_model.pth", map_location=torch.device("cpu"))
    )
    model.eval()
    return model

model = load_model()

st.title("💊 AI Drug-Target Binding Affinity Predictor")
st.markdown(
    "Predict small-molecule binding affinity ($\text{pK}_\text{d}$) directly from molecular 2D graphs using **PyTorch Geometric GCN**."
)

smiles_input = st.text_input(
    "Enter SMILES string:",
    "CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5",
)

if st.button("Predict Binding Affinity"):
    mol = Chem.MolFromSmiles(smiles_input)
    if mol:
        col1, col2 = st.columns([1, 1])
        with col1:
            st.image(
                Draw.MolToImage(mol, size=(300, 300)),
                caption="2D Chemical Structure",
            )

        # Convert to Graph
        atom_feats = [
            [
                a.GetAtomicNum(),
                a.GetDegree(),
                1.0 if a.GetIsAromatic() else 0.0,
                float(a.GetHybridization()),
            ]
            for a in mol.GetAtoms()
        ]
        x = torch.tensor(atom_feats, dtype=torch.float)
        edge_idx = []
        for bond in mol.GetBonds():
            edge_idx.extend(
                [
                    [bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()],
                    [bond.GetEndAtomIdx(), bond.GetBeginAtomIdx()],
                ]
            )
        edge_index = (
            torch.tensor(edge_idx, dtype=torch.long).t().contiguous()
            if len(edge_idx) > 0
            else torch.empty((2, 0), dtype=torch.long)
        )
        batch = torch.zeros(x.size(0), dtype=torch.long)

        with torch.no_grad():
            pred_pkd = model(x, edge_index, batch).item()

        with col2:
            st.metric(
                label="Predicted Binding Affinity ($pK_d$)",
                value=f"{pred_pkd:.2f}",
            )
            if pred_pkd >= 8.0:
                st.success("High Binding Affinity (Potent Lead Compound)")
            elif pred_pkd >= 6.0:
                st.info("Moderate Binding Affinity")
            else:
                st.warning("Low Binding Affinity")
    else:
        st.error("Invalid SMILES format.")
